version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    volumes:
      - type: bind
        source: ./my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
